version: '3'

services:
  fox-assistant:
    container_name: telegram-bot
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
