version: '3'

services:
  fox-assistant:
    container_name: bots
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VK_TOKEN=${VK_TOKEN}
    working_dir: /app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
